name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  # test-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./
  #       with:
  #         client_id: ${{ secrets.CLIENT_ID }}
  #         client_secret: ${{ secrets.CLIENT_SECRET }}
  #     - name: 'Use nucleus CLI'
  #       run: 'nucleus -h'
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set nucleus debug env
        id: debug
        run: |
          echo "NUCLEUS_DEBUG_ENV=stage" >> $GITHUB_ENV
      - uses: ./
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
      - name: 'Use nucleus CLI'
        run: 'nucleus -h'
